version: '3'

services:

  nginx:
    build: ./build/nginx
    ports:
    - 80:80
    networks:
    - appnet
    volumes:
    - ./app:/var/www/html

  php:
    build: ./build/php
    environment:
      DB_PORT: 3306
      DB_HOST: db
    networks:
    - appnet
    volumes:
    - ./app:/var/www/html

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: lumen
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    networks:
    - appnet
    volumes:
    - dbdata:/var/lib/mysql

networks:
  appnet:

volumes:
  dbdata: